### ISSUE TITLE
Standardise documentation format

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/missions#15]
You guys have been writing documentation for a while. For the next set of technical tasks, you will be collaborating on the same document. Time to level-up!

For this reason, I'd like you to standardise on the writing style so that everyone is on the same page. Young Ee is the documentation guru so he'll take the lead.

The documentation format will be your creation and your baby. Unless the docu guidelines have glaring issues, I shall refrain from influencing the outcome too much. Some pointers on drafting guidelines:
1. Consider making documentation simple, readable and easy to maintain
1. Consider standardising things that are frequently used (eg. headers) and are important to you (eg. specifying the language, say `bash` or `python`, in code blocks)
1. Consider future refactoring of documentation. Make it easy for the poor fella who has to do it.
1. Consider saying `Always preview your code` before publishing it.
1. Consider using text editors such as `Sublime Text` (it's my fav btw) plus the markdown plugin to preview the code before you do a PR.

The homework is... churn out a `Cloud Commandos guide to awesome documentation`. It's kinda like [NASA's design guidelines](https://www.nasa.gov/image-feature/nasa-graphics-standards-manual) but purely for documentation. I'm not looking for a full-blown guide so 1 page with a few paras would suffice. The guide is a living document for newbies and to serve as a reminder to yourselves when you're rusty. From time to time, the documentation guru will eyeball everyone's work to ensure alignment.

**Comment by youngee91** [comment]
Hi @eugene-chow, I have created the [documentation guidelines](https://github.com/CloudCommandos/admin/blob/master/CC-Documentation-Guidelines.md) at the admin repository. 

Please have a look and do let me know if i am doing it right. Thanks!

**Comment by eugene-chow** [comment]
LGTM. Next time, do a PR instead. That way the appropriate changes can be suggested.

@CloudCommandos/infra please burn and drink the guide. As you write docs and find better ways to do things, please update this best-practices guide.

Thanks Young Ee!
